### ISSUE TITLE
is this project still alive?

### ISSUE THREAD

**Issue by mncrftfrcnm** [Fluxyn/PyModMC#7]
quite a promising idea, but is anybody still making code for this?

**Comment by widikov** [comment]
💀

**Comment by Elyas2024** [comment]
this project is an amazing idea, why is it dead?

**Comment by GirlInPurple** [comment]
> this project is an amazing idea, why is it dead?

> quite a promising idea, but is anybody still making code for this?

Theres a few reasons for this. I hope you dont mind if i get a bit technical, but simply put:

- There is no built in support for Python in Java. You would need to either rely on the heavily outdated Jython library, or make your own Python > Java transpiler, which while not impossible, is probably not a good idea.
  - This project currently uses the transpiling method, it just writes a bunch of Java to a file and adds in data as needed using F-strings.
  - I checked just now, apparently Jython is in the process of updating to Python 3, but they're currently stuck on Python 2.7.13, and have been stuck on for nearly a decade!
- Theres no demand for it, as there are many alternatives out there. Take KubeJS, JS Macros, and MCreator for example.
  - JS Macros has a Python extension, but its *very* limited and cant do what mods can do. The mod is primarily made for making your own macros and AFK scripts after all.
- Writing in Java/Kotlin/Scala, and having deeper access into Minecraft's and the JVM codebase is far preferred over a wrapper around a modding framework.
  - KubeJS gets around this by adding tons of hooks that allow you to access these parts, but only specified parts thats the KubeJS team allow you to access. You can always write an extension, but that requires knowing Java, so back to step one.
  - I havnt even mentioned Mixins yet, those *need* to be written in Java to work properly due to how the Mixin library works. If you can somehow compile Python into JVM Bytecode, then *i guess* mixins are possible, but back to square one with the Python > Java conversion again!
- Not to mention that this project compiles mods for i believe 1.18 (1.18 and 1.19 code look similar enough its hard to distinguish), a version that is around 2 years old. Updating this to 1.21 would be *a lot* of work, as the changes in the engine of the game were so large they caused big name mods like Litematica to stop officially updating past 1.20.4, and was the nail in the coffin for me to stop modding too.
  - This does not mean that newer projects will have the same issues. The problems come in when updating the NBT format to the new Components format, and there has been little to no progress on a conversion tool as far as im aware. (If im wrong about this someone please correct me!) This is why Sodium, a mod that barely touches the NBT format, updated basically Immediately, while Litematica, a mod that is focused around the NBT format and uses it in it's schematics, hit EOL recently.

If you really want to make a mod, learn either Java or Kotlin and watch [Kaupenjoe's](https://youtube.com/playlist?list=PLKGarocXCE1EO43Dlf5JGh7Yk-kRAXUEJ) modding tutorials. They're really good and its what pushed me to start modding, and eventually start making my own game. If you dont want to go that route, [MCreator](https://mcreator.net/) is also a good option, and if you know JavaScript, [KubeJS](https://kubejs.com/) is an option for simple things too.\
As for learning Java, [W3 Schools](https://www.w3schools.com/java/) and [GeeksForGeeks](https://www.geeksforgeeks.org/java/) are good places to start. Also, the [Fabric](https://fabricmc.net/) community is pretty welcoming, and is actually what this project uses internally, feel free to join their Discord if you have any questions.

**Comment by mncrftfrcnm** [comment]
@GirlInPurple  Thanks for the explanation. I understood most of the things you said before commenting, but your comment was still informative. Also I guess author abandoned his git hub account, so we most likely will not get any updates any day soon.
